# Generated by Django 5.0.2 on 2024-02-27 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contract_contractrule_customerplan_parkmovement_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrule',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_rules', to='base.contract'),
        ),
    ]
