# Generated by Django 5.0.2 on 2024-02-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contractrule_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicle'),
        ),
    ]
